decrypt:
  rubygems.yml: repo/rubygems.yml.asc
assets:
  s3cfg: yegor256/home#assets/s3cfg
install: |
  sudo apt-get install -y bcrypt
  bundle install
  sudo gem install pdd
release:
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/rultor/version.rb
    gem build rultor.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
    pdd --source=$(pwd) --verbose --file=/dev/null
  commanders:
  - yegor256
architect:
- yegor256
- alex-palevsky
merge:
  commanders: []
deploy: {}
